### ISSUE TITLE
Cannot install package with composer

### ISSUE THREAD

**Issue by pgodiani** [simialbi/yii2-kanban#1]
Seems that the dependency with swiper cannot be resolved when installing the package:

$ **composer require "simialbi/yii2-kanban" "~1.0@dev"**
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for simialbi/yii2-kanban ~1.0@dev -> satisfiable by simialbi/yii2-kanban[1.0.x-dev].
    - **simialbi/yii2-kanban 1.0.x-dev requires bower-asset/swiper ^4.5.0 -> no matching package found**.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by simialbi** [comment]
You have to add `asset-packagist` as repository source as described on:
https://asset-packagist.org/
