### ISSUE TITLE
bower-asset/swiper/dist not found

### ISSUE THREAD

**Issue by paskuale75** [simialbi/yii2-kanban#11]
The file or directory to be published does not exist: /.../myApp/vendor/bower-asset/swiper/dist 

I checked the vendors folder, but I can't find the `/dist `folder in the 'swiper' folder
![bower_swiper](https://user-images.githubusercontent.com/9800/131806446-2ea9dcad-649c-45cc-a9e6-184bc9c01aa1.png)

**Comment by paskuale75** [comment]
[probable solution]
in _vendor/simialbi/yii2-kanban/src/KanbanSwiperAsset.php_ file update this:
`public $sourcePath = '@bower/swiper/src';` and it work for me...

**Comment by simialbi** [comment]
Which version of kanban do you have intalled?
In the current version, it is exactly this path: https://github.com/simialbi/yii2-kanban/blob/master/src/KanbanSwiperAsset.php#L18
