### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted (tried to allocate 11691172 bytes)

### ISSUE THREAD

**Issue by yii2backendwebdeveloper** [simialbi/yii2-kanban#13]
![screenshot-127 0 0 1-2021 11 17-14_52_30](https://user-images.githubusercontent.com/68148299/142172987-9db76723-df32-4428-a34e-a7559b195768.png)
![screenshot-127 0 0 1-2021 11 17-14_51_52](https://user-images.githubusercontent.com/68148299/142172999-c47d8c10-f037-4dea-bb86-594f5cf25d74.png)

**Comment by simialbi** [comment]
@yii2backendwebdeveloper Thx for the feedback. 
With which version did it happen?

**Comment by simialbi** [comment]
@yii2backendwebdeveloper I have a suggestion why it was. Icon Library could use much of ram. I replaced with rmrevin ones. The problem should be solved.
