### ISSUE TITLE
Integration into Humhub tasks (sponsored)

### ISSUE THREAD

**Issue by olantrust** [simialbi/yii2-kanban#4]
Users over at Humhub are keen for a Kanban view that can be integrated with the existing Tasks module.
https://github.com/humhub/humhub-modules-tasks/issues/115

Olan Trust is willing to sponsor work on it @simialbi @ykweb  please message ict @ olan . uk if interested.

**Comment by simialbi** [comment]
@olantrust Thanks for your interest in this module. What do you have in mind? A fork rewritten with HumHub Classes (e.g. extending HumHub ActiveRecord etc.)? Or some "adapter" translating kanban classes to HumHub Classes? Or extending existing HumHub tasks module with functionality of this module?
It's not so easy to solve this without having to maintain 2 repositories...

**Comment by olantrust** [comment]
Hi @simialbi, yes indeed I guess expanding the existing Humhub Tasks module might be the best way to proceed...

**Comment by simialbi** [comment]
Moved to discussion: https://github.com/simialbi/yii2-kanban/discussions/5
