### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by ry1980** [simialbi/yii2-kanban#8]
hi simialbi!
i don't understand how i can run this project.... i've installed this package, i've set the config file adding the modules section, created the user class etc...but after all how can i access this module? how can i get the kanban board? with which url/route?
....projectname/web/kanban return a 404 error

**Comment by simialbi** [comment]
Hi @ry1980 
Thanks for your feedback. 
Can you please paste your app config (at least module and urlManager config)?
Do you have pretty urls enabled?

**Comment by ry1980** [comment]
hi simialbi,
this is my composr.json
`{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0",
        "moonlandsoft/yii2-phpexcel": "*",
        "yiisoft/yii2-jui": "~2.0.0",
        "kartik-v/yii2-widget-select2": "dev-master",
        "simialbi/yii2-kanban": "^1.8"

    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.1.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/codeception": "^4.0",
        "codeception/verify": "~0.5.0 || ~1.1.0",
        "codeception/specify": "~0.4.6",
        "symfony/browser-kit": ">=2.7 <=4.2.4",
        "codeception/module-filesystem": "^1.0.0",
        "codeception/module-yii2": "^1.0.0",
        "codeception/module-asserts": "^1.0.0"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}`
my console.php
`<?php

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$config = [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'app\commands',
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
        '@tests' => '@app/tests',
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User'
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,

    ],
    'modules' => [
        'kanban' => [
            'class' => 'simialbi\yii2\kanban\Module'
        ]
    ],


    'params' => $params,
    /*
    'controllerMap' => [
        'fixture' => [ // Fixture generation command line.
            'class' => 'yii\faker\FixtureController',
        ],
    ],
    */
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
    ];
}

return $config;
`
and my web.php
`<?php

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';

$config = [
    'id' => 'basic',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
        '@adminlte/widgets'=>'@vendor/adminlte/yii2-widgets'

    ],
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => 'ooUMw1_-x4aKFiUga2ue_gMMOneJ4DKI',
        ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'identityClass' => 'app\models\User',
            'enableAutoLogin' => true,
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'encryption' => 'ssl',
                'host' => 'smtp.gmail.com',
                'port' => '465',
                'username' => 'hd@ennova.it',
                'password' => '7YiGIlEG',
            ],           ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
        
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],

        
    ],
    'language' => 'it-IT',
    'params' => $params,
];

if (YII_ENV_DEV) {
    // configuration adjustments for 'dev' environment
    $config['bootstrap'][] = 'debug';
    $config['modules']['debug'] = [
        'class' => 'yii\debug\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        'allowedIPs' => ['127.0.0.1', '::1','192.168.33.*'],
    ];

    $config['bootstrap'][] = 'gii';
    $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        // uncomment the following to add your IP if you are not connecting from localhost.
        'allowedIPs' => ['127.0.0.1', '::1','192.168.33.*'],
    ];
}

return $config;
`
thanks in advance


`

**Comment by simialbi** [comment]
Remove the password pls from your config

**Comment by simialbi** [comment]
You have to add the
```php
    'modules' => [
        'kanban' => [
            'class' => 'simialbi\yii2\kanban\Module'
        ]
    ],
```
section in the `web.php` file too

**Comment by ry1980** [comment]
hi!
i've added the module section in web.php ..run migration and it works!
i have another login section and i've removed the user_id variable..i see the create bord form...create bucket ...when i try to create a new task it doesn't work...not save nothing...the schedule section doesn't save nothing too...when i move the task in the calendar not change any value on db ... (i've manually created tasks into db)

**Comment by ry1980** [comment]
is there any demo or tutorial?thx in advance

**Comment by ry1980** [comment]
maybe the create form task doesn't work because there isn't the Ticket model....the model ticket.php file is missing

**Comment by simialbi** [comment]
Can you give me some URL? So I could give a look?

**Comment by simialbi** [comment]
And the Ticket model is only needed if you'd like to link kanban with [Ticket Tool](https://github.com/simialbi/yii2-ticket)

**Comment by ry1980** [comment]
i'm working locally , i don't have any url to give to you to test this....so the ticket model is not mandatory...the logic flow is :board creation, bucket creation, task creation...  what does the monitoring section do?

**Comment by simialbi** [comment]
The Monitorig is meant to create lists of workers, you'd like to monitor their tasks. You can create a list with members and the system generates statistics and filterable lists of tasks for this users.

**Comment by ry1980** [comment]
ah wonderful!very useful! thx!

**Comment by simialbi** [comment]
But now you managed to get it running it properly?

**Comment by ry1980** [comment]
yes now i can save the task ...there was a validation problem with the date format

**Comment by simialbi** [comment]
Ok, What date format do you use?

**Comment by ry1980** [comment]
y-m-d format

**Comment by simialbi** [comment]
Thank you. I'll give a try.
So I can close this issue?
